spring:
  data:
    mongodb:
      uri: ${DB_URL}
      database: journaldb
      auto-index-creation: true

server:
  port: ${PORT}
  servlet:
    context-path: /

weather:
  api:
    key: ${WEATHER_API}